name: sin_flix
description: A movie application case study.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9 # If you have SVG assets
  lottie: ^3.0.0
  cached_network_image: ^3.3.1

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

  get_it: ^7.6.4
  injectable: ^2.3.2

  go_router: ^13.0.1

  flutter_secure_storage: ^9.0.0

  dartz: ^0.10.1
  image_picker: ^1.0.7
  intl: ^0.20.2 # Also used by gen-l10n

  firebase_core: ^3.13.1
  firebase_analytics: ^11.4.6
  firebase_crashlytics: ^4.3.6
  firebase_storage: ^12.4.6
  firebase_auth: ^5.5.4
  flutter_native_splash: ^2.3.9

  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.2
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: assets/logo/splash_logo.png
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/

  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf