// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd6sRrs8vLbHvMcaQa2pLtqmUPecHrSeA',
    appId: '1:545584884417:web:c035a5977392e0db014240',
    messagingSenderId: '545584884417',
    projectId: 'casestudy-movie',
    authDomain: 'casestudy-movie.firebaseapp.com',
    storageBucket: 'casestudy-movie.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjHyV4oQZ_RhAXwLWNtD5Qg8dnPqJF3II',
    appId: '1:545584884417:android:c3e0100eec8b45e6014240',
    messagingSenderId: '545584884417',
    projectId: 'casestudy-movie',
    storageBucket: 'casestudy-movie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiIPsQHm64G6OognGH6dt-DbBiJDSJr9c',
    appId: '1:545584884417:ios:6d6c978ce23ff7df014240',
    messagingSenderId: '545584884417',
    projectId: 'casestudy-movie',
    storageBucket: 'casestudy-movie.firebasestorage.app',
    iosBundleId: 'com.example.casestudy',
  );
}
