// lib/core/di/injector.dart
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'injector.config.dart';                             // <- generated file
import 'package:sin_flix/features/home/presentation/cubit/liked_cubit.dart';

final getIt = GetIt.instance;

@InjectableInit(
  initializerName: r'$initGetIt',                          // ← as you had
  preferRelativeImports: true,
  asExtension: false,
)
Future<void> configureDependencies() async {
  // 1️⃣  register everything generated by injectable
  $initGetIt(getIt);

  // 2️⃣  add the manual singleton for Likes
  getIt.registerLazySingleton<LikedCubit>(() => LikedCubit());
}
